version: '3.3'

services:
  database:
    image: postgres:13
    container_name: "localpg"
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=osvani
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54320:5432'
    volumes: 
      - postgresql-volume:/var/lib/postgresql/data
volumes:
  postgresql-volume:
    external: true

